### ISSUE TITLE
Fails when there is no .desktop file in the "Accessories" category.

### ISSUE THREAD

**Issue by depadiernos** [BlackCodec/MenuGenerator#1]
Getting the following after running `menugenerator -i -p -w jwm`

```
Traceback (most recent call last):
  File "/usr/bin/menugenerator", line 266, in <module>
    main(sys.argv[1:]}
  File "/usr/bin/menugenerator", line 254, in main
    tempmenu = CreateFluxMenu()
  File "/usr/bin/menugenerator", line 154, in CreateFluxboxMenu
    if CurrentRunning['Options']['Categories']['Icons'][tempcategoryname] != ' ':
KeyError: 'Accessories'
```

Also, the menugenerator does not create `.config/menugenerator` folder if it is not found, but produces an error instead.

**Comment by BlackCodec** [comment]
Resolved.
Now if the folder doesn't exist it create them.
Also if the category specified is not defined in xdg menu it create them empty.

Refer to release 0.4.
